(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function i(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function t(r){if(r.ep)return;r.ep=!0;const n=i(r);fetch(r.href,n)}})();const o={form:document.querySelector("#search-form"),moviesList:document.querySelector("#list-movies"),loader:document.querySelector(".loader"),title:document.querySelector("#main-title"),resetBtn:document.querySelector("#reset-btn"),loadMoreBtn:document.querySelector("#load-more")},f=e=>e!=null&&e.length?e.map(({poster_path:s,title:i,release_date:t,overview:r})=>`
        <li class="movie-item">
            <img
                class="movie-poster"
                src="https://image.tmdb.org/t/p/w300/${s}"
                alt="${i}"
                loading="lazy"
            />
            <div class="movie-info">
                <div>
                    <h3 class="movie-title">${i}</h3>
                    <div class="movie-year">${t||"-"}</div>
                </div>
                <p class="movie-overview">
                    ${r}
                </p>
            </div>
        </li>
        `).join(""):!1,g=()=>{o.moviesList.innerHTML=""},c=(e=!1)=>{o.loader.classList[e?"add":"remove"]("active")},h=(e=!1)=>{o.resetBtn.classList[e?"add":"remove"]("active")},u=(e=!1)=>{o.loadMoreBtn.classList[e?"add":"remove"]("active")},d="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiZDU5NjBkZmE3YmY3ODdkYTU5NzdjMzA4NzkyNjcxOCIsIm5iZiI6MTYwMzQ4NTg3NC4wNDgsInN1YiI6IjVmOTM0MGIyN2ViNWYyMDA1YTAwY2ZhNiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.-35wsiUmFgUrlSH8Ef-TWv01vcbpp5ysK7oX-BURKOM",v=async(e=1)=>{try{const s={method:"GET",headers:{Accept:"application/json",Authorization:`Bearer ${d}`,"Content-Type":"application/json;charset=utf-8"}};return(await fetch(`https://api.themoviedb.org/3/trending/movie/week?page=${e}`,s)).json()}catch{return alert("Помилка сервера"),!1}},y=async(e="",s=1)=>{if(!e)return!1;try{const i={method:"GET",headers:{Accept:"application/json",Authorization:`Bearer ${d}`,"Content-Type":"application/json;charset=utf-8"}};return(await fetch(`https://api.themoviedb.org/3/search/movie?query=${e}&page=${s}`,i)).json()}catch{return alert("Помилка сервера"),!1}};let l=1,p=!0,m="";async function L(){var s;l=1,m="",g(),c(!0);const e=await v(l);if(((s=e==null?void 0:e.results)==null?void 0:s.length)>0){const i=f(e==null?void 0:e.results);c(!1),(e==null?void 0:e.page)<(e==null?void 0:e.total_pages)&&(u(!0),l=(e==null?void 0:e.page)+1),o.moviesList.insertAdjacentHTML("beforeend",i),o.title.innerHTML="Найпопулярніші фільми за тиждень"}else c(!1),o.title.innerHTML="Поки що найпопулярніші фільми не доступні";p=!0,h(!1)}o.form.addEventListener("submit",async e=>{var i;e.preventDefault();const s=e.target.movie.value.trim();if(s&&s!==""){l=1,p=!1,m=s,g(),c(!0);const t=await y(s,l);if(((i=t==null?void 0:t.results)==null?void 0:i.length)>0){const r=f(t==null?void 0:t.results);c(!1),(t==null?void 0:t.page)<(t==null?void 0:t.total_pages)&&(u(!0),l=(t==null?void 0:t.page)+1),o.moviesList.insertAdjacentHTML("beforeend",r),o.title.innerHTML=`Результат пошук за запитом: ${s}`}else c(!1),o.title.innerHTML="Немає результату за Вашим запитом :(";o.form.reset(),h(!0)}else alert("Введіть значення!")});o.resetBtn.addEventListener("click",L);o.loadMoreBtn.addEventListener("click",async()=>{var s,i;if(c(!0),u(!1),p){const t=await v(l);if(((s=t==null?void 0:t.results)==null?void 0:s.length)>0){const r=f(t==null?void 0:t.results);c(!1),(t==null?void 0:t.page)<(t==null?void 0:t.total_pages)&&(u(!0),l=(t==null?void 0:t.page)+1),o.moviesList.insertAdjacentHTML("beforeend",r)}else c(!1);return}const e=await y(m,l);if(((i=e==null?void 0:e.results)==null?void 0:i.length)>0){const t=f(e==null?void 0:e.results);c(!1),(e==null?void 0:e.page)<(e==null?void 0:e.total_pages)&&(u(!0),l=(e==null?void 0:e.page)+1),o.moviesList.insertAdjacentHTML("beforeend",t)}else c(!1)});L();
//# sourceMappingURL=index.js.map
